version: "3.8"
services:
  mongodb:
    image: 'mongo' # points to pre-existing image
    volumes: 
      - data:/data/db
    container_name: mongodb
  # environment:
    # - MONGO_INITDB_ROOT_USERNAME=max
    # MONGO_INITIDB_ROOT_USERNAME: max
  # env_file:
      # - ./env/mongo.env
  backend:
    build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - logs:/app/logs
      - ./backend:/app # bind mount
      - /app/node_modules # anonymous volumes
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true # tells docker it needs open input connection
    tty: true # -it flag
    depends_on:
      - backend

# named volumes
volumes:
  data:
  logs: